export type ShortcutsType = {
    a?: HTMLAnchorElement[];
    b?: HTMLAnchorElement[];
    c?: HTMLAnchorElement[];
    d?: HTMLAnchorElement[];
    e?: HTMLAnchorElement[];
    f?: HTMLAnchorElement[];
    g?: HTMLAnchorElement[];
    i?: HTMLAnchorElement[];
    j?: HTMLAnchorElement[];
    k?: HTMLAnchorElement[];
    l?: HTMLAnchorElement[];
    m?: HTMLAnchorElement[];
    n?: HTMLAnchorElement[];
    o?: HTMLAnchorElement[];
    p?: HTMLAnchorElement[];
    q?: HTMLAnchorElement[];
    r?: HTMLAnchorElement[];
    s?: HTMLAnchorElement[];
    t?: HTMLAnchorElement[];
    u?: HTMLAnchorElement[];
    v?: HTMLAnchorElement[];
    w?: HTMLAnchorElement[];
    x?: HTMLAnchorElement[];
    y?: HTMLAnchorElement[];
    z?: HTMLAnchorElement[];
};